var $_name = "",
    _$ageOfPerson = 20,
    placeOfBirth = "",
    userId = 2,
    userResponse = "";
var Name = "",
    Placeofbirth = "",
    Cityname = "",
    mypersonality = "",
    biodata = "";